### PR TITLE
Uniform responses

### LINKED ISSUE #3: Responses need to be more uniform
Right now, the way responses are returned is very un-uniform.
For example, the action `validate_user` returns an array containing either true or false, and the `get_content` action returns the content as JSON.
At any time, however, if there is some error, it will return an error object:
```json
{
  "error": true,
  "message": "Something went wrong..."
}
```

All responses need to have this basic format:
```
{
  "error": true | false,
  "data": --response--,
  "code": "ERROR_CODE" | "OK"
}
```
Where --response-- is of type `boolean | Object | string`.

### PR DESCRIPTION
**Pull request by Vehmloewff**
Fixes #3

### CODE REVIEW

File: actions/validate_user.php [hunk 1]
```diff
@@ -1,12 +1,10 @@
 <?php
 if ($email && $password) {
     if (validateUser($conn, $email, $password) == true) {
-        $response = array(true);
+        responseBuilder(false, "Valid user.", "OK");
     } else {
-        $response = array(false);
+        responseBuilder(true, "Invalid user!", "INVALID_USER");
```
Comment (Vehmloewff) [inline actions/validate_user.php]: I would prefer this file to return a boolean for the data, not a string.

**Review by Vehmloewff — COMMENTED** [review]
This is all I can think of right now.

**Comment by Vehmloewff** [comment]
You missed one!
https://github.com/Vehmloewff/jikno-backend-api/blob/master/api.php#L14
